events {
    worker_connections 1024;
}

http {
    # conf.d 아래의 설정 포함
    include /etc/nginx/conf.d/community.conf;
    include /etc/nginx/conf.d/api.conf;
    include /etc/nginx/conf.d/portainer.conf;
}
