name: 아무말 대잔치 PROD CICD 파이프라인

# 어떤 브랜치에서 쓰이는 지
on:
  push:
    branches:
      - develop

# CICD JOBS
jobs:

  # 통합 테스트 환경 구축
  test:
    runs-on: ubuntu-22.04

    # 통합 테스트용 컨테이너 띄우기
    services:
      # Mysql
      mysql:
        image: mysql:8.0
        ports:
          - '3306:3306'
        env:
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}

      # 레디스
      redis:
        image: redis:7.2.5
        ports:
          - '6379:6379'

    # 스텝 실행하기
    steps:
      - name: 체크아웃
        uses: actions/checkout@v4

      - name: 자바 설치하기
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Gradle 캐싱
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}

      - name: application-test.yml 넣기
        run: |
          mkdir -p src/integrationTest/resources
          echo "${{secrets.APPLICATION_TEST_YML}}" > ./src/integrationTest/resources/application-test.yml

      - name: 통합 및 단위 테스트 진행하기
        run: |
          ./gradlew clean check -Dspring.profiles.active=test

  # 테스트가 모두 통과했을 때만, 도커 이미지 빌드 + 푸시하기
  build-push-image:
    runs-on: ubuntu-22.04
    needs: test
    if: success()
    steps:
      - name: 체크아웃
        uses: actions/checkout@v4

      - name: AWS 자격 증명 설정
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_KEY}}
          aws-region: ${{secrets.AWS_REGION}}

      - name: 도커 이미지 빌드 및 태그
        run: |
          docker build --platform linux/amd64 -t ktb-be:latest .
          docker tag ktb-be:latest ${{secrets.AWS_ECR_BE}}/ktb/be:latest

      - name: ECR 로그인하기
        run: |
          aws ecr get-login-password --region ${{secrets.AWS_REGION}} | docker login --username AWS --password-stdin ${{secrets.AWS_ECR_BE}}

      - name: ECR 푸시
        run: |
          docker push ${{secrets.AWS_ECR_BE}}/ktb/be:latest
